/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueadero;
import java.util.ArrayList;
/**
 *
 * @author Portátil de Fonso
 */

public class Interfaz_Parqueadero extends javax.swing.JFrame {
    
    ArrayList<Bici> bicicletas = new ArrayList<Bici>();
    ArrayList<moto> motos = new ArrayList<moto>();
    ArrayList<carrito> carritos = new ArrayList<carrito>();
    int sum=0;
    public Interfaz_Parqueadero() {
        initComponents();
    }
    public String totminutos(String hrsin, String hrsout){
        int hora1= Integer.parseInt(hrsin.substring(0,2));
        int minutos1= Integer.parseInt(hrsin.substring(3));
        int hora2= Integer.parseInt(hrsout.substring(0,2));
        int minutos2= Integer.parseInt(hrsout.substring(3));
        int sumhora= hora2-hora1;
        int summinutos= minutos1+minutos2;
        int tothora=sumhora*60;
        int tot=tothora+summinutos;
        return String.valueOf(tot);
    }
    public void crearbici(){
        String placa= PlacaIng.getText();
        String hr = HoraIng.getText();
        Bici aux=new Bici(hr, placa);
        bicicletas.add(aux);
        sum++;
        TotalGuard.setText(String.valueOf(sum));
    }
    public void crearcarro(){
        String placa= PlacaIng.getText();
        String hr = HoraIng.getText();
        carrito aux=new carrito(hr, placa);
        carritos.add(aux);
        sum++;
        TotalGuard.setText(String.valueOf(sum));
    }
    public void crearmoto(){
        String placa= PlacaIng.getText();
        String hr = HoraIng.getText();
        moto aux=new moto(hr, placa);
        motos.add(aux);
        sum++;
        TotalGuard.setText(String.valueOf(sum));
    }
    public void deletebici(Bici bc){
        
        bc=null;
        System.gc();
        sum--;
        TotalGuard.setText(String.valueOf(sum));
        
    }
    public void deletecarro(carrito c){
        c=null;
        System.gc();
        sum--;
        TotalGuard.setText(String.valueOf(sum));
    }
    public void deletemoto(moto m){
        m=null;
        System.gc();
        sum--;
        TotalGuard.setText(String.valueOf(sum));
    }public void paybici(Bici bc){
        String hrin=bc.getHorain();
        String hrout=HoraOut.getText();
        Labeltot.setText(totminutos(hrin,hrout));
    }
    public void paycarro(carrito bc){
        String hrin=bc.getHorain();
        String hrout=HoraOut.getText();
        Labeltot.setText(totminutos(hrin,hrout));
    }
    public void paymoto(moto bc){
        String hrin=bc.getHorain();
        String hrout=HoraOut.getText();
        Labeltot.setText(totminutos(hrin,hrout));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBicis = new javax.swing.JRadioButton();
        btnmotos = new javax.swing.JRadioButton();
        carros = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Labeltot = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        PlacaIng = new javax.swing.JTextField();
        HoraIng = new javax.swing.JTextField();
        PlacaOut = new javax.swing.JTextField();
        HoraOut = new javax.swing.JTextField();
        In = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TotalGuard = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        btnexitcarro = new javax.swing.JRadioButton();
        btnexitmoto = new javax.swing.JRadioButton();
        btnexitbici = new javax.swing.JRadioButton();
        pagartotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("ENTRADA:");
        jLabel1.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("SALIDA:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DE VEÍCULO:");

        Grupo1.add(btnBicis);
        btnBicis.setForeground(new java.awt.Color(255, 255, 255));
        btnBicis.setText("Bicicletas y Ciclomotores (20/min)");

        Grupo1.add(btnmotos);
        btnmotos.setForeground(new java.awt.Color(255, 255, 255));
        btnmotos.setText("Motocicletas (30/min)");

        Grupo1.add(carros);
        carros.setForeground(new java.awt.Color(255, 255, 255));
        carros.setText("Carros (60/min)");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PLACA:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HORA DE INGRESO");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HORA DE SALIDA:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PLACA:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MINUTOS");

        Labeltot.setForeground(new java.awt.Color(255, 255, 255));
        Labeltot.setText("00");

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        PlacaIng.setText("Ingrese Placa");
        PlacaIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaIngActionPerformed(evt);
            }
        });

        HoraIng.setText("Ingrese Hora");
        HoraIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraIngActionPerformed(evt);
            }
        });

        PlacaOut.setText("Ingrese Placa");
        PlacaOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaOutActionPerformed(evt);
            }
        });

        HoraOut.setText("Ingrese Hora");
        HoraOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraOutActionPerformed(evt);
            }
        });

        In.setText("GUARDAR AUTO");
        In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Guardados:");

        TotalGuard.setForeground(new java.awt.Color(255, 255, 255));
        TotalGuard.setText("00");

        Exit.setText("PAGAR");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnexitcarro);
        btnexitcarro.setForeground(new java.awt.Color(255, 255, 255));
        btnexitcarro.setText("Carros (60/min)");

        buttonGroup2.add(btnexitmoto);
        btnexitmoto.setForeground(new java.awt.Color(255, 255, 255));
        btnexitmoto.setText("Motocicletas (30/min)");

        buttonGroup2.add(btnexitbici);
        btnexitbici.setForeground(new java.awt.Color(255, 255, 255));
        btnexitbici.setText("Bicicletas y Ciclomotores (20/min)");

        pagartotal.setForeground(new java.awt.Color(255, 255, 255));
        pagartotal.setText("00");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL A PAGAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBicis)
                            .addComponent(btnmotos)
                            .addComponent(carros))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalGuard)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HoraIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(In))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlacaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlacaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoraOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Labeltot)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Exit)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(eliminar)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnexitbici)
                            .addComponent(btnexitmoto)
                            .addComponent(btnexitcarro)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagartotal)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(TotalGuard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBicis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmotos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carros)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PlacaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HoraIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(In)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnexitbici)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexitmoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnexitcarro)
                            .addComponent(eliminar))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PlacaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(HoraOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Labeltot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pagartotal))
                        .addGap(3, 3, 3)))
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String marcaexit;
        int minutos;
         if(btnexitbici.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < bicicletas.size(); i++){
               if(bicicletas.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   
                   deletebici(bicicletas.get(i));
                   break;
               }
            }
           
            
        } else if(btnexitmoto.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < motos.size(); i++){
               if(motos.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   
                   deletemoto(motos.get(i));
                   break;
               }
            }
           
           
        } else if(btnexitcarro.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < carritos.size(); i++){
               if(carritos.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   
                   deletecarro (carritos.get(i));
                   break;
               }
            }
           
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void PlacaIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaIngActionPerformed

    private void HoraIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraIngActionPerformed

    private void PlacaOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaOutActionPerformed

    private void HoraOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraOutActionPerformed

    private void InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InActionPerformed
        if(btnBicis.isSelected()){
            crearbici();
            
        } else if(btnmotos.isSelected()){
            crearmoto();
        } else if(carros.isSelected()){
            crearcarro();
        }
        
    }//GEN-LAST:event_InActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        String marcaexit;
        int minutos;
         if(btnexitbici.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < bicicletas.size(); i++){
               if(bicicletas.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   paybici(bicicletas.get(i));
                   deletebici(bicicletas.get(i));
                   break;
               }
            }
           minutos= Integer.valueOf(Labeltot.getText());
           int dinero= minutos*20;
           pagartotal.setText(String.valueOf(dinero));
            
        } else if(btnexitmoto.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < motos.size(); i++){
               if(motos.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   paymoto(motos.get(i));
                   deletemoto(motos.get(i));
                   break;
               }
            }
           minutos= Integer.valueOf(Labeltot.getText());
           int dinero= minutos*30;
           pagartotal.setText(String.valueOf(dinero));
           
        } else if(btnexitcarro.isSelected()){
            marcaexit=PlacaOut.getText();
            
            for(int i = 0; i < carritos.size(); i++){
               if(carritos.get(i).getPlaca().equalsIgnoreCase(marcaexit)){
                   paycarro(carritos.get(i));
                   deletecarro (carritos.get(i));
                   break;
               }
            }
           minutos= Integer.valueOf(Labeltot.getText());
           int dinero= minutos*60;
           pagartotal.setText(String.valueOf(dinero));
        }
        
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Parqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JTextField HoraIng;
    private javax.swing.JTextField HoraOut;
    private javax.swing.JButton In;
    private javax.swing.JLabel Labeltot;
    private javax.swing.JTextField PlacaIng;
    private javax.swing.JTextField PlacaOut;
    private javax.swing.JLabel TotalGuard;
    private javax.swing.JRadioButton btnBicis;
    private javax.swing.JRadioButton btnexitbici;
    private javax.swing.JRadioButton btnexitcarro;
    private javax.swing.JRadioButton btnexitmoto;
    private javax.swing.JRadioButton btnmotos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton carros;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pagartotal;
    // End of variables declaration//GEN-END:variables
}
