/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino;
import javax.swing.ImageIcon;

/**
 *
 * @author Portátil de Fonso
 */
public class Dados extends javax.swing.JFrame {
    int c=0;
    int in=0;
    int dad1;
    int dad2;
    int sumaTotal;
    //Timer timer = new Timer();
    boolean detener= false;
    public void detenerHilos(){
        detener=true;
    }
    public synchronized void activarHilos(){
        detener=false;
        notifyAll();
        
    }
    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {
                while (detener) {
                    synchronized (Dados.this) {
                        try {
                            Dados.this.wait();
                        }catch (InterruptedException e) {
                            // Manejar interrupción si es necesario
                        }
                    }
                }
                for (int i = 0; i<20; i++) {
                    int num= (int)(Math.random()*100+1);
                    Dado1.setIcon(new ImageIcon(Dados.this.getClass().getResource("/casino/"+num%6+".jpg")));
                    
                    try{
                        Thread.sleep(100);
                    } catch(InterruptedException e){
                    }
                    if(i==19){
                        detenerHilos();
                    }
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        // Manejar interrupción si es necesario
                    }
                    dad1=(num%6)+1; 
                }
            }
        }
    });
    Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {
                while (detener) {
                    synchronized (Dados.this) {
                        try {
                            Dados.this.wait();
                        }catch (InterruptedException e) {
                            // Manejar interrupción si es necesario
                        }
                    }
                }
                for (int i = 0; i<20; i++) {
                    int num= (int)(Math.random()*100+1);
                    Dado2.setIcon(new ImageIcon(Dados.this.getClass().getResource("/casino/"+num%6+".jpg"))); 
                    
                    try{
                        Thread.sleep(100);
                    } catch(InterruptedException e){
                    }
                    if(i==19){
                        detenerHilos();
                    }
                    try {
                        Thread.sleep(110);
                    } catch (InterruptedException e) {
                        // Manejar interrupción si es necesario
                    }
                    
                    dad2=(int)(num%6)+1; 
                    //System.out.print(dad2);
                }
                
                suma.setText(""+(dad1+dad2));
            }
        }
    });
     public Dados() {
        initComponents();
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dado1 = new javax.swing.JLabel();
        Girar = new javax.swing.JButton();
        Dado2 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Girar.setText("TIRAR");
        Girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Girar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(suma)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dado1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(Dado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(suma)
                .addGap(45, 45, 45)
                .addComponent(Girar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirarActionPerformed
        in++;
        if(in==1){
            t.start();
            t1.start();
        } else{
          activarHilos(); 
          
        }
        
     
    }//GEN-LAST:event_GirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dado1;
    private javax.swing.JLabel Dado2;
    private javax.swing.JButton Girar;
    private javax.swing.JLabel suma;
    // End of variables declaration//GEN-END:variables
}
